spring:
  jpa:
    show-sql: true

logging:
  level:
    kr.co.unionsystems: DEBUG

upload:
  dir: ${UPLOAD_DIR:./uploads}

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
