-- V17: 프론트엔드 하드코딩 데이터를 DB로 이관 (dataware_schema)
-- 공지사항, 이벤트, 동영상, 고객사례

-- ═══════════════════════════════════════
-- 1. 공지사항 (posts, category=NOTICE)
-- ═══════════════════════════════════════
INSERT INTO dataware_schema.posts (title, slug, content, excerpt, category, thumbnail_url, published, view_count, created_at) VALUES
('DA#_DQ_Edition 조달청 나라장터 등록', 'da-dq-edition-g2b', E'데이터 비즈니스 전문기업 엔코아(대표 이화식)가 자사의 ''데이터웨어 디에이샵 디큐에디션(DATAWARE DA#_DQ Edition)''이 조달청 나라장터에 등록되었다고 밝혔다.\n\nDA#_DQ Edition은 데이터 모델링 툴 DA#과 데이터 품질관리 솔루션 DQ#의 품질진단 기능을 하나의 패키지로 구성한 제품이다.\n\n최근 데이터 표준화와 데이터 품질관리는 데이터 관리 프로세스의 기반이 되는 필수 항목으로, DA#_DQ Edition은 데이터 표준화 기반의 체계적인 품질진단을 지원하며 공공데이터 품질관리 수준평가에 대응하기 위한 최적의 툴을 제공한다.\n\n편리한 모델링 기능과 강력한 품질진단 기능을 하나의 패키지에서 사용할 수 있어 도입 비용 절감과 운영 효율성 향상이 가능하다.', 'DA#-DQ# 패키지로 구성해 데이터 표준화 기반의 체계적인 품질진단 지원. 공공데이터 품질관리 수준평가에 대응하기 위한 최적의 툴 제공.', 'NOTICE', '/images/uniondata/0.png', true, 0, '2021-11-22'),
('[리뷰] 데이터 품질진단 DA# DQ_Edition', 'review-da-dq-edition', E'지속되고 있는 코로나19 팬데믹 사태는 비즈니스 환경을 빠르게 변화시키고 있다. 비대면이 활성화되고 재택근무가 일상이 되면서 정보를 공유할 수 있는 클라우드의 활용은 필수적이 되었고, 공유된 정보와 온라인상에서 정보 보호를 위하여 개인정보보호를 위한 컴퓨팅도 많이 활용되고 있다.\n\n엔코아가 제안하는 디에이샵 디큐 에디션은 데이터 모델링과 품질진단을 한 번에 지원하는 솔루션으로 데이터 모델링 툴 DA#과 데이터 품질관리 솔루션 DQ#의 품질진단 기능을 하나의 패키지로 구성한 제품이다.\n\n출처: IT DAILY', '데이터 모델링과 품질진단 자동화로 관리 효율성 향상. 코로나19 팬데믹 사태로 비대면 활성화와 클라우드 활용이 필수적인 시대.', 'NOTICE', '/images/uniondata/0-1.png', true, 0, '2021-06-02'),
('[리뷰] 데이터모델링 DA#', 'review-da-sharp', E'체계적인 기업의 데이터 품질 관리는 데이터 모델링에서 시작된다. DA#은 차세대 프로젝트에서 단위 업무 모델링까지 폭넓게 활용되며, 개발 생산성과 성능을 높이는 핵심 도구이다.\n\n다중 DBMS 지원, Undo/Redo 편집, 다양한 형태의 산출물 제공 등 편의성을 갖추고 있으며, Repository 기반 팀 모델링과 웹 실시간 VIEW 기능으로 협업 생산성을 극대화한다.\n\n출처: IT DAILY', '차세대 프로젝트에서 단위 업무 모델링까지, 개발 생산성과 성능 제고. 데이터 비즈니스의 기본, 데이터 모델링 툴.', 'NOTICE', '/images/uniondata/0000.png', true, 0, '2021-06-01'),
('DA# DQ_Edition GS인증 1등급', 'da-dq-edition-gs-cert', E'엔코아(대표 이화식)가 데이터 표준화 기반 데이터 품질진단 솔루션 ''디에이샵 디큐 에디션(DA# DQ_Edition)''이 굿소프트웨어(GS)인증 1등급을 획득했다고 밝혔다.\n\nGS인증은 한국정보통신기술협회(TTA)가 소프트웨어의 기능성, 신뢰성, 효율성, 사용성, 유지보수성, 이식성 등 국제표준(ISO/IEC 25023) 기반 품질특성을 시험하여 인증하는 제도로, 1등급은 최고 등급이다.\n\nDA# DQ_Edition은 데이터 모델링과 품질진단을 하나의 패키지로 제공하여 데이터 관리의 효율성을 극대화한 제품이다.', '엔코아가 데이터 표준화 기반 데이터 품질진단 솔루션 DA# DQ Edition이 굿소프트웨어(GS)인증 1등급을 획득했다고 밝혔다.', 'NOTICE', '/images/uniondata/0000-1.png', true, 0, '2021-05-30'),
('유니온시스템즈 DA# 리뉴얼 오픈', 'da-sharp-renewal-open', E'넓어진 화면, 모바일 검색, 디지털 환경 변화에 맞춰 정보를 전달하는데 기존의 홈페이지는 부족함이 있었습니다.\n\n이번 리뉴얼을 통해 DA#과 DA# DQ_Edition 기능, 모델링도구 팁과 활용법, 칼럼, 온&오프라인 참여 가능한 교육 등 다양한 정보를 보다 쉽게 확인하실 수 있습니다.\n\n앞으로도 유니온시스템즈는 고객 여러분께 더 나은 서비스를 제공하기 위해 지속적으로 노력하겠습니다.', '넓어진 화면, 모바일 검색, 디지털 환경 변화에 맞춰 정보를 전달하는데 기존 홈페이지는 부족함이 있었습니다.', 'NOTICE', '/images/uniondata/board__notice.png', true, 0, '2021-05-01'),
('엔코아·유니온시스템즈 DA# 총판 협약', 'encore-unionsystems-dealer-agreement', E'엔코아(대표 이화식)가 데이터 통합관리 솔루션 ''데이터웨어(DATAWARE)'' 주력 제품인 데이터 모델링 툴 ''디에이샵(DA#)'' 시장 확대를 위해 유니온시스템즈와 총판 협약을 체결했다.\n\n이번 총판 협약을 통해 유니온시스템즈는 DA# 및 DATAWARE 제품군의 판매, 기술지원, 교육 등 전반적인 비즈니스를 담당하게 된다.\n\n 엔코아 이화식 대표는 "유니온시스템즈는 데이터 거버넌스 분야에서 풍부한 경험과 전문성을 보유한 파트너로, 이번 협약을 통해 DA# 제품의 시장 확대와 고객 서비스 강화에 큰 시너지가 기대된다"고 전했다.', '엔코아가 데이터 통합관리 솔루션 DATAWARE 주력 제품인 데이터 모델링 툴 DA# 시장 확대를 위해 유니온시스템즈와 총판 협약을 체결했다.', 'NOTICE', '/images/uniondata/board__notice.png', true, 0, '2021-02-24');

-- ═══════════════════════════════════════
-- 2. 이벤트 (posts, category=EVENT)
-- ═══════════════════════════════════════
INSERT INTO dataware_schema.posts (title, slug, content, excerpt, category, thumbnail_url, published, view_count, detail_json, created_at) VALUES
('2025 DA# 조달 캠페인', 'event-2025-jodal', E'2025 연말 맞이 DA# 조달 구매 캠페인입니다.\n\nNO.1 데이터 모델링 툴 DA# 도입과 함께 따뜻한 한 끼를 전하세요!\n솔루션 도입을 넘어 사회적 가치 실현까지!\n\n• 대상: 조달청 나라장터를 통한 DA# 신규 구매 고객\n• 혜택: 구매 고객 전원 기부 참여 + 무료 교육 제공\n• 문의: 02-706-8999', '2025 연말 맞이 DA# 조달 구매 캠페인. NO.1 데이터 모델링 툴 DA# 도입과 함께 따뜻한 한 끼를 전하세요!', 'EVENT', '/images/uniondata/%EC%9C%A0%EB%8B%88%EC%98%A82025DA_%EC%A1%B0%EB%8B%AC%EA%B5%AC%EB%A7%A4%EC%BA%A0%ED%8E%98%EC%9D%B8.png', true, 0, '{"tag":"이벤트","tagColor":"#36c88a","status":"진행중"}', '2025-11-03'),
('DA~드리는 DA# 여름 할인 이벤트', 'event-2025-summer', E'AI 시대 데이터 자산화 전략 START!\n\nDA# 여름 할인 이벤트\n빠른 결정, 더욱 합리적인 혜택!\n\n• 기간: 2025년 7월 1일 ~ 8월 29일\n• 대상: DA# 신규 구매 고객\n• 혜택: 특별 할인가 적용\n• 문의: 02-706-8999', 'AI 시대 데이터 자산화 전략 START! DA# 여름 할인 이벤트. 빠른 결정, 더욱 합리적인 혜택!', 'EVENT', '/images/uniondata/0707_head.png', true, 0, '{"tag":"프로모션","tagColor":"#f59e0b","status":"진행중"}', '2025-07-01'),
('2025 을사년 맞이 BBAM! 프로모션', 'event-2025-bbam', E'2025년 을사년 맞이 BBAM! 프로모션\n\n기간 내 신규 구매 고객께 BBAM!하게 드리는 구매 프로모션입니다.\n\n• 기간: 2025년 2월 3일 ~ 3월 31일\n• 대상: DA# 신규 구매 고객\n• 견적 문의: 02-706-8999', '2025년 을사년 맞이 기간 내 신규 구매 고객께 BBAM!하게 드리는 구매 프로모션.', 'EVENT', '/images/uniondata/0000.png', true, 0, '{"tag":"프로모션","tagColor":"#f59e0b","status":"종료"}', '2025-02-03'),
('DATAWARE DA# 통합 패키지 출시 이벤트', 'event-2024-total-package', E'DATAWARE DA# 통합 패키지 출시 이벤트\n\n4개 제품 스펙을 하나의 라이선스로!\nDA# 통합 패키지 출시 기념 이벤트입니다.\n\n• 혜택: 제품 구매 문의 고객 선착순 30분께 모바일 주유권 제공\n• 포함 제품: DA# Architecture + DQ Edition + Contents Builder + AI Powered Pack\n• 문의: 02-706-8999', '4개 제품 스펙을 하나의 라이선스로! DA# 통합 패키지 출시 기념 이벤트.', 'EVENT', '/images/uniondata/0000-1.png', true, 0, '{"tag":"이벤트","tagColor":"#36c88a","status":"종료"}', '2024-11-29'),
('DA# 보상판매 이벤트', 'event-2024-trade-in', E'국산 모델링 S/W 시장 점유율 및 인지도 1위 기념!\n\n2024 데이터 모델링 툴 DA# 보상판매 이벤트\n최대 55% 할인!\n\n• 기간: 2024년 10월 1일 ~ 12월 31일\n• 조건: 기존 타 브랜드 정품 보유 시 인증 조건으로 할인 구매 가능\n• 할인가: 8,970,000원 → 4,000,000원\n• 문의: 02-706-8999', '국산 모델링 S/W 시장 점유율 및 인지도 1위 기념! 최대 55% 할인!', 'EVENT', '/images/uniondata/2023_thum.jpg', true, 0, '{"tag":"프로모션","tagColor":"#f59e0b","status":"종료"}', '2024-03-31'),
('2024 갑진년 맞이 값진 구매 프로모션', 'event-2024-dragon', E'2024 갑진년 맞이 값진 구매 프로모션\n\n2024 청룡의 해 갑진년 맞이\n유니온시스템즈와 함께 하는 값진 구매 프로모션!\n\n• 혜택: 선착순 24분께만 드리는 특별 혜택\n• 문의: 02-706-8999', '2024 청룡의 해 갑진년 맞이 유니온시스템즈와 함께 하는 값진 구매 프로모션!', 'EVENT', '', true, 0, '{"tag":"프로모션","tagColor":"#f59e0b","status":"종료"}', '2024-01-23'),
('DA# 프로젝트 라이선스 출시 이벤트', 'event-2022-project-license', E'DA# 프로젝트 라이선스 출시 이벤트\n\n• 기간: 2023.01.01 ~ 2023.12.31\n• 문의: 02-706-8999', 'DA# 프로젝트 라이선스 출시 이벤트', 'EVENT', '', true, 0, '{"tag":"이벤트","tagColor":"#36c88a","status":"종료"}', '2022-12-06'),
('공공데이터 품질관리 수준평가 대응 설명회', 'event-2022-public-data', E'공공데이터 품질관리 수준평가 대응 설명회\n\n• 문의: 02-706-8999', '공공데이터 품질관리 수준평가 대응 설명회', 'EVENT', '/images/uniondata/0922-001.png', true, 0, '{"tag":"설명회","tagColor":"#8b5cf6","status":"종료"}', '2022-08-26'),
('ERD 시연, 데이터 관계파악 설명회', 'event-2022-erd', E'ERD 시연, 데이터 관계파악 설명회\n\n• 문의: 02-706-8999', 'ERD 시연, 데이터 관계파악 설명회', 'EVENT', '', true, 0, '{"tag":"설명회","tagColor":"#8b5cf6","status":"종료"}', '2022-03-14'),
('찾아가는 데이터모델링 DA# 설명회', 'event-2022-da-seminar', E'찾아가는 데이터모델링 DA# 설명회\n\n• 문의: 02-706-8999', '찾아가는 데이터모델링 DA# 설명회', 'EVENT', '', true, 0, '{"tag":"설명회","tagColor":"#8b5cf6","status":"종료"}', '2022-02-08');

-- ═══════════════════════════════════════
-- 3. 동영상 (posts, category=VIDEO)
-- ═══════════════════════════════════════
INSERT INTO dataware_schema.posts (title, slug, content, excerpt, category, thumbnail_url, published, view_count, detail_json, created_at) VALUES
('새로운 시대의 데이터모델링 — 이화식 대표', 'video-da5-ep1', '', 'DA#5 런칭 세미나 Episode 1', 'VIDEO', '', true, 0, '{"youtubeId":"33nGO8uZOQ8","speaker":"이화식 대표 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 1","tag":"세미나","tagColor":"#36c88a"}', '2021-11-10'),
('개발스토리 — 정철원 디렉터', 'video-da5-ep2', '', 'DA#5 런칭 세미나 Episode 2', 'VIDEO', '', true, 0, '{"youtubeId":"CLsXPIB6EH4","speaker":"정철원 디렉터 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 2","tag":"세미나","tagColor":"#36c88a"}', '2021-11-11'),
('기본구조 및 개념 — 최광희 연구원', 'video-da5-ep3', '', 'DA#5 런칭 세미나 Episode 3', 'VIDEO', '', true, 0, '{"youtubeId":"V-8w2lXyiqY","speaker":"최광희 연구원 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 3","tag":"세미나","tagColor":"#36c88a"}', '2021-11-11'),
('달라진 모델링 — 정민수 연구원', 'video-da5-ep4', '', 'DA#5 런칭 세미나 Episode 4', 'VIDEO', '', true, 0, '{"youtubeId":"YMyKMXM3m4U","speaker":"정민수 연구원 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 4","tag":"세미나","tagColor":"#36c88a"}', '2021-11-11'),
('API 그리고 편의기능 — 김기동 연구원', 'video-da5-ep5', '', 'DA#5 런칭 세미나 Episode 5', 'VIDEO', '', true, 0, '{"youtubeId":"CN93yT8UL44","speaker":"김기동 연구원 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 5","tag":"세미나","tagColor":"#36c88a"}', '2021-11-11'),
('초보자도 할 수 있는 현행모델 파헤치기 — 이임형 연구원', 'video-da5-ep6', '', 'DA#5 런칭 세미나 Episode 6', 'VIDEO', '', true, 0, '{"youtubeId":"1qP1zbsChQc","speaker":"이임형 연구원 (엔코아)","series":"DA#5 런칭 세미나","episode":"Episode 6","tag":"세미나","tagColor":"#36c88a"}', '2021-11-11'),
('물리객체생성', 'video-da5-tut1', '', 'DA#5 튜토리얼 Tutorial 1', 'VIDEO', '', true, 0, '{"youtubeId":"HA7kcXJ3IIo","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 1","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22'),
('여러물리모델', 'video-da5-tut2', '', 'DA#5 튜토리얼 Tutorial 2', 'VIDEO', '', true, 0, '{"youtubeId":"T1ZCYyOyL3Q","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 2","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22'),
('서식적용', 'video-da5-tut3', '', 'DA#5 튜토리얼 Tutorial 3', 'VIDEO', '', true, 0, '{"youtubeId":"RXHDtaAUBKs","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 3","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22'),
('DB 리버스', 'video-da5-tut4', '', 'DA#5 튜토리얼 Tutorial 4', 'VIDEO', '', true, 0, '{"youtubeId":"jwNKCliYAEw","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 4","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22'),
('리버스 후 모델 자동 배치', 'video-da5-tut5', '', 'DA#5 튜토리얼 Tutorial 5', 'VIDEO', '', true, 0, '{"youtubeId":"OAFBHAElESQ","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 5","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22'),
('자동관계생성', 'video-da5-tut6', '', 'DA#5 튜토리얼 Tutorial 6', 'VIDEO', '', true, 0, '{"youtubeId":"t12UZTlIR80","speaker":"엔코아 기술지원팀","series":"DA#5 튜토리얼","episode":"Tutorial 6","tag":"튜토리얼","tagColor":"#60a5fa"}', '2021-11-22');

-- ═══════════════════════════════════════
-- 4. 고객사례 (customer_stories)
-- ═══════════════════════════════════════
INSERT INTO dataware_schema.customer_stories (company, slug, industry, title, content, thumbnail_url, logo_url, published, detail_json, created_at) VALUES
('오늘의집', 'ohouse', '유통', '버킷플레이스, 데이터 품질진단 솔루션 공급', '명확한 데이터 표준 관리와 품질관리로 사용자에게 보다 편리하고 최적의 고객 경험을 제공하기 위해 DA# DQ_Edition을 도입', '/images/uniondata/clients_img_ssg.png', '', true, '{"companyDesc":"올인원 라이프 스타일 플랫폼 오늘의집 운영사 버킷플레이스","pageHeading":"버킷플레이스, 데이터 품질진단 솔루션 공급","background":["컨텐츠/커머스/커뮤니티 유기적으로 결합된 서비스","회원 수와 빠르게 증가하는 데이터 관리"],"features":["DA# DQ_Edition"],"effects":["명확한 데이터 표준 관리, 품질관리","개발 생산성, 편의성 제고, 데이터 의사결정 활용"],"quote":"버킷플레이스 관계자는 \"명확한 데이터 표준 관리와 품질관리로 사용자에게 보다 편리하고 최적의 고객 경험을 제공하기 위해 DA# DQ_Edition을 도입하게 됐다\"며 \"데이터 모델링과 품질진단을 하나의 패키지 도입으로 해결할 수 있어 효율적으로 활용할 수 있을 것으로 기대하고 있다\"고 전했다.","quoteSource":"디지털데일리","meta":{"date":"2021-11-26","industry":"유통","purpose":"그룹웨어, 데이터 효과적 활용 기반 마련"}}', '2021-11-26'),
('SSG닷컴', 'ssg', '유통', 'SSG닷컴이 데이터를 활용하는 법', '데이터를 설계하여 구성원들이 데이터를 비즈니스에 활용하는 것이 데이터모델링의 목적이다.', '/images/uniondata/clients_img_ssg.png', '', true, '{"companyDesc":"신세계 그룹의 온라인 쇼핑 포털 SSG닷컴을 운영하는 이커머스 기업","pageHeading":"SSG닷컴이 데이터를 활용하는 법","background":["방대한 데이터의 수집·저장·통합·활용 등 전 과정을 효과적으로 관리의 필요성","따로 운영되던 유통 서비스를 단일 채널로 통합하기 위한 용어 표준화 필요"],"features":["DA#, DQ#, META# 을 통한 서비스 단일채널 통합","용어 표준화, 전사 데이터 현행화·표준화"],"effects":["기획팀 – 개발팀 소통 원활화","데이터 효과적 활용 기반마련","데이터 품질 향상","계보 관리로 향상된 데이터 프로세스 마련"],"quote":"데이터의 품질을 높이고, 데이터베이스를 설계하여 구성원들이 데이터를 비즈니스에 활용하는 것이 데이터모델링의 목적이다.","quoteSource":"컴퓨터월드","meta":{"date":"2021-11-11","industry":"유통","purpose":"그룹웨어, 데이터 효과적 활용 기반 마련"}}', '2021-11-11'),
('한국수자원공사', 'kwater', '공공기관', '한국수자원공사, 데이터 관리 포털 구축', '데이터 관리 포털 구축 프로젝트는 여타 다른 기업·기관의 프로젝트에 비해 요구사항도 많고 필요한 기능이 많았다.', '/images/uniondata/clients_img_kwater.png', '', true, '{"companyDesc":"국내의 모든 수자원 관리를 담당하는 환경부 산하 공기업","pageHeading":"한국수자원공사, 데이터 관리 포털 구축","background":["현업 담당자들에게 객관적인 데이터 관련 서비스 제공","데이터모델 기반 테이블 변경 관리 체계를 구축하여 데이터 구조 품질확보","비즈니스 분류 관리 및 시스템/DB서버/테이블/컬럼의 메타데이터를 관리하는 데이터 전문 솔루션 도입"],"effects":["개발 생산성, 편의성 제고, 데이터 활용 극대화","데이터모델(ERD) 기반 테이블 변경 프로세스 구축","IT부서 중심의 DB를 다양한 사용자가 활용할 수 있도록 시스템 구축"],"quote":"정보화 사업은 힘들고 어려운 프로젝트다. 수자원공사가 진행한 데이터 관리 포털 구축 프로젝트는 여타 다른 기업·기관의 프로젝트에 비해 요구사항도 많고 필요한 기능이 많았다.","quoteSource":"컴퓨터월드","meta":{"date":"2021-11-11","industry":"공공기관","purpose":"데이터 효과적 활용 기반 마련, 프로세스 구축"}}', '2021-11-11'),
('아모레퍼시픽', 'amore', '유통', '아모레퍼시픽, 메타데이터 관리체계 고도화', '현장의 영업, 마케팅, 생산자가 데이터를 활용하여 의사결정과 업무에 활용할 수 있도록 하는 것이 목표다.', '/images/uniondata/clients_img_amore.png', '', true, '{"companyDesc":"화장품, 생활용품, 건강식품 등을 생산, 판매하는 대한민국 대표적인 화장품 기업","pageHeading":"아모레퍼시픽, 메타데이터 관리체계 고도화","background":["전사 데이터 표준 및 모델관리 프로세스 개선과 시스템 구축","시스템 운영 수준 향상 및 장기적인 고품질 데이터 체계 기반 마련","효율적인 데이터 활용 및 분석을 위한 데이터 기반 비즈니스 의사결정 시스템 구축"],"features":["DATAWARE의 DA#, META# 활용","데이터 아키텍트, 데이터 설계·표준화·모델링 자체 수행"],"effects":["필요한 시점 데이터를 분석해 실시간 의사결정 도출 기반마련","데이터 리터러시 구축으로 마케팅, 영업 경쟁력 강화"],"quote":"데이터를 자체적으로 분석하고 다루는 환경이 안 되면 데이터 기반 영업과 마케팅이 근본적으로 불가능한 시대가 됐다.","quoteSource":"디지털타임스","meta":{"date":"2021-11-11","industry":"유통","purpose":"실시간 의사결정 도출 기반마련, 경쟁력 강화"}}', '2021-11-11'),
('현대해상', 'hyundai-marine', '금융', '현대해상, 메타데이터 관리시스템 재구축', '메타데이터를 통한 애플리케이션, 정보, 시스템 관리와 비즈니스 의사결정에 데이터 활용', '/images/uniondata/clients_img_hyundai-marine.png', '', true, '{"companyDesc":"1955년 3월 5일 설립, 1999년 현대그룹에서 분리된 해상보험 전업회사","pageHeading":"현대해상, 메타데이터 관리시스템 재구축","background":["메타데이터 시스템의 노후화로 인한 유지보수 및 지원 부재","운영인원 감소 및 관리대상 시스템 증가로 인한 효율적인 프로세스 필요"],"effects":["메타데이터를 통한 애플리케이션, 정보, 시스템 관리","축적된 데이터의 효율적 관리의 필요성 비즈니스 의사결정에 데이터 활용"],"quote":"단독으로 데이터 관리만을 위한 목적으로 메타데이터 관리솔루션 도입은 의미가 없다. 비즈니스 플로우를 통해 조직 내부에서 유동성 있게 데이터를 활용할 수 있는 환경 구축이 중요하다.","meta":{"date":"2021-11-10","industry":"금융","purpose":"그룹웨어, 데이터 효과적 활용 기반 마련"}}', '2021-11-10'),
('동양생명', 'dongyang-life', '금융', '동양생명, 데이터 관리체계 자동화 솔루션 도입', '노후화된 메타데이터 솔루션 교체 및 모델링 솔루션 도입으로 데이터 관리체계 자동화 구현', '/images/uniondata/clients_img_tong-yang-life.png', '', true, '{"companyDesc":"1989년 동양베네피트생명으로 설립된 생명보험 전문기업","pageHeading":"동양생명, 데이터 관리체계 자동화 솔루션 도입","background":["노후화된 메타데이터 솔루션 교체 및 모델링 솔루션 도입","모델 변경사항을 CSR 시스템으로 DB에 연동하여 반영","모델 현행화를 위한 표준 갭 분석"],"features":["DA#, META# 기반 데이터 관리 자동화"],"effects":["데이터 품질관리를 통한 고품질 데이터 확보","소통 원활화 및 운영 효율성 개선","데이터 기반 비즈니스 의사결정 지원","전사 IT 자산 관리 환경 제공"],"quote":"메타데이터 관리는 대용량 데이터 중 원하는 정보를 효율적으로 찾아낼 수 있도록 다른 데이터를 설명해 주는 데이터를 관리하는 것이다.","meta":{"date":"2021-11-10","industry":"금융","purpose":"데이터 관리체계 자동화, 고품질 데이터 확보"}}', '2021-11-10');
